// text = text.replace(/lj/g, 'ль')
// text = text.replace(/nj/g, 'нь')
// text = text.replace(/ś/g, 'сь')
// text = text.replace(/ź/g, 'зь')
// text = text.replace(/ě/g, 'ѣ')
// text = text.replace(/y/g, 'ы')

const vucko = text => text
  // prvo dupla
  .replace(/lj/g, 'љ')
  .replace(/Lj/g, 'Љ')
  .replace(/LJ/g, 'Љ')
  .replace(/nj/g, 'њ')
  .replace(/Nj/g, 'Њ')
  .replace(/NJ/g, 'Њ')
  .replace(/dž/g, 'џ')
  .replace(/Dž/g, 'Џ')
  .replace(/DŽ/g, 'Џ')
  // mala
  .replace(/a/g, 'а')
  .replace(/b/g, 'б')
  .replace(/c/g, 'ц')
  .replace(/č/g, 'ч')
  .replace(/ć/g, 'ћ')
  .replace(/d/g, 'д')
  .replace(/đ/g, 'ђ')
  .replace(/e/g, 'е')
  .replace(/f/g, 'ф')
  .replace(/g/g, 'г')
  .replace(/h/g, 'х')
  .replace(/i/g, 'и')
  .replace(/j/g, 'ј')
  .replace(/k/g, 'к')
  .replace(/l/g, 'л')
  .replace(/m/g, 'м')
  .replace(/n/g, 'н')
  .replace(/o/g, 'о')
  .replace(/p/g, 'п')
  .replace(/r/g, 'р')
  .replace(/s/g, 'с')
  .replace(/š/g, 'ш')
  .replace(/t/g, 'т')
  .replace(/u/g, 'у')
  .replace(/v/g, 'в')
  .replace(/z/g, 'з')
  .replace(/ž/g, 'ж')
  // velika
  .replace(/A/g, 'А')
  .replace(/B/g, 'Б')
  .replace(/C/g, 'Ц')
  .replace(/Č/g, 'Ч')
  .replace(/Ć/g, 'Ћ')
  .replace(/D/g, 'Д')
  .replace(/Đ/g, 'Ђ')
  .replace(/E/g, 'Е')
  .replace(/F/g, 'Ф')
  .replace(/G/g, 'Г')
  .replace(/H/g, 'Х')
  .replace(/I/g, 'И')
  .replace(/J/g, 'Ј')
  .replace(/K/g, 'К')
  .replace(/L/g, 'Л')
  .replace(/M/g, 'М')
  .replace(/N/g, 'Н')
  .replace(/O/g, 'О')
  .replace(/P/g, 'П')
  .replace(/R/g, 'Р')
  .replace(/S/g, 'С')
  .replace(/Š/g, 'Ш')
  .replace(/T/g, 'Т')
  .replace(/U/g, 'У')
  .replace(/V/g, 'В')
  .replace(/Z/g, 'З')
  .replace(/Ž/g, 'Ж')

export default function transliterate(text, script) {
  return script === 'lat' ? text : vucko(text)
}
